schema = 1

[targets.clod]
description = "clod code rules the world"
yolo = true
compose = ["space:defaults@dev", "space:praesidium-defaults@dev"]


[targets.ralph-plan]
description = "Ralph planning loop"
compose = ["space:ralph-plan-loop@dev", "space:praesidium-defaults@dev"]

[targets.ralph-build]
description = "Ralph build loop"
compose = ["space:ralph-build-loop@dev"]

[targets.smokey]
yolo = true
description = "Smoke test runner"
compose = ["space:smokey@dev", "space:defaults@stable"]
